name = "MultiFractalFields"
uuid = "424b133d-7d37-4eca-9954-b7e5ab009cd0"
authors = ["Andre Considera"]
version = "0.1.0"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
